/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: Multipainkiller Studio (https://sketchfab.com/Multipainkiller_Studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guy-fawkes-mask-v1-free-ffdc746cabc647259fc494c151dc3d8f
Title: Guy Fawkes Mask - v.1 FREE
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.M_Goatee} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.M_Mask} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
