/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 tim.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tim.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tim.geometry} material={materials.texture} />
    </group>
  )
}

useGLTF.preload('/tim.gltf')
